// What this does: base old Cribbit Telegram/Web shell tokens extracted from the old app visual system.
// Key invariant: presentation only; no gameplay or command authority lives in CSS.
// Explicitly out of scope: new landing-page themes or backend/runtime configuration.
export const OLD_UI_BASE_STYLES = String.raw`
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#03050a;color:#f7f8fb;--tg-display-font:"Arial Narrow","Roboto Condensed","Helvetica Neue",sans-serif;--tg-bg:#03050a;--tg-panel:#090d15;--tg-panel-2:#0d121d;--tg-border:#30384a;--tg-border-soft:rgba(255,255,255,.09);--tg-muted:#8d95a4;--tg-text:#f7f8fb;--tg-lime:#9cff16;--tg-purple:#b34cff;--tg-pink:#ff2f87;--tg-cyan:#38cfff;--tg-orange:#ff861d;--tg-gold:#ffd329;--tg-danger:#ff466d;--tg-surface-shadow:0 14px 32px rgba(0,0,0,.3);--bg:var(--tg-bg);--surface:var(--tg-panel);--surface2:var(--tg-panel-2);--text:var(--tg-text);--muted:var(--tg-muted);--line:var(--tg-border-soft);--lime:var(--tg-lime);--magenta:var(--tg-pink);--purple:var(--tg-purple);--cyan:var(--tg-cyan);--orange:var(--tg-orange);--gold:var(--tg-gold);--red:var(--tg-danger)}
*{box-sizing:border-box}html,body{margin:0;min-width:100%;min-height:100%;background:var(--tg-bg)}body{min-height:var(--cribbit-platform-height,100dvh);overflow-x:hidden}button,input,select{font:inherit}button{-webkit-tap-highlight-color:transparent}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid var(--tg-lime);outline-offset:2px}#app{min-height:var(--cribbit-platform-height,100dvh)}
.cribbit-app{min-height:100dvh;color:var(--tg-text);background:var(--tg-bg);font-family:inherit}.cribbit-app.tg-app{width:min(100%,430px);min-height:var(--cribbit-platform-height,100dvh);margin:0 auto;padding:calc(var(--cribbit-safe-top,0px) + 10px) max(14px,var(--cribbit-safe-right,0px)) calc(var(--cribbit-safe-bottom,0px) + 24px) max(14px,var(--cribbit-safe-left,0px));background:radial-gradient(circle at 8% 0%,rgba(156,255,22,.09),transparent 28%),radial-gradient(circle at 94% 10%,rgba(179,76,255,.13),transparent 30%),radial-gradient(circle at 52% 72%,rgba(56,207,255,.035),transparent 36%),linear-gradient(180deg,#03050a 0%,#060811 48%,#03050a 100%)}
.cribbit-app button,.cribbit-app input,.cribbit-app select{font:inherit;color:inherit}.cribbit-app button{appearance:none;-webkit-appearance:none;background:none}.cribbit-app input{appearance:none;-webkit-appearance:none}.cribbit-app button:disabled{opacity:.42;cursor:not-allowed}
.tg-app__header{display:grid;grid-template-columns:44px minmax(0,1fr) 44px;align-items:center;gap:10px;min-height:58px;padding-bottom:10px;border-bottom:1px solid rgba(179,76,255,.24)}.tg-app__title-block{display:flex;min-width:0;flex-direction:column;align-items:center}.tg-app__title-block strong{max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:21px;line-height:1.05;letter-spacing:-.025em}.tg-app__title-block span{margin-top:4px;color:#a4a9b4;font-size:11px}
.tg-icon-button{display:grid;place-items:center;width:42px;height:42px;padding:0;border:1px solid rgba(179,76,255,.48);border-radius:14px;background:linear-gradient(180deg,rgba(18,20,30,.96),rgba(7,9,15,.98));color:#ce73ff;box-shadow:inset 0 0 0 1px rgba(255,255,255,.025),0 0 18px rgba(179,76,255,.07);font-size:20px;font-weight:900;cursor:pointer}.tg-icon-button--back{color:var(--tg-lime);border-color:rgba(156,255,22,.36)}
.tg-live-strip{display:flex;align-items:center;justify-content:center;gap:9px;min-height:42px;margin:10px 0;padding:8px 14px;border:1px solid rgba(156,255,22,.58);border-radius:12px;background:linear-gradient(180deg,rgba(156,255,22,.07),rgba(156,255,22,.025));color:var(--tg-lime);box-shadow:0 0 18px rgba(156,255,22,.08),inset 0 0 0 1px rgba(156,255,22,.04);font-family:var(--tg-display-font);font-size:12px;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.tg-live-strip>span:last-child{margin-left:auto;color:#aeb5c0;letter-spacing:.04em}.tg-live-dot{width:9px;height:9px;flex:0 0 auto;border-radius:50%;background:var(--tg-lime);box-shadow:0 0 14px var(--tg-lime)}
.connection-status{display:flex;align-items:center;gap:6px;min-width:0;color:#9fa6b2;font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.connection-status i{width:7px;height:7px;flex:0 0 auto;border-radius:50%;background:var(--tg-lime);box-shadow:0 0 10px var(--tg-lime)}.connection-status span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.connection-status[data-connection="reconnecting"] i{background:var(--tg-orange);box-shadow:0 0 10px var(--tg-orange)}.connection-status[data-connection="offline"] i{background:var(--tg-danger);box-shadow:0 0 10px var(--tg-danger)}
@media(min-width:760px){.cribbit-app.tg-app{width:min(100%,520px)}}@media(prefers-color-scheme:light){:root{color-scheme:dark}html,body,.cribbit-app{background:var(--tg-bg);color:var(--tg-text)}}
`;
