export const CANONICAL_IDENTITY_MIGRATION_SQL = "create extension if not exists pgcrypto;\n\ncreate table if not exists users (\n  id text primary key default gen_random_uuid()::text,\n  display_name text not null,\n  display_username text,\n  avatar_url text,\n  created_at timestamptz not null default now(),\n  updated_at timestamptz not null default now()\n);\n\ncreate table if not exists user_identities (\n  id uuid primary key default gen_random_uuid(),\n  user_id text not null references users(id) on delete cascade,\n  provider text not null check (provider in ('telegram', 'web_password')),\n  provider_user_id text not null,\n  provider_username text,\n  provider_payload jsonb not null default '{}'::jsonb,\n  created_at timestamptz not null default now(),\n  unique (provider, provider_user_id),\n  unique (user_id, provider)\n);\n\ncreate table if not exists web_credentials (\n  user_id text primary key references users(id) on delete cascade,\n  login_username text not null unique,\n  password_hash text not null,\n  created_at timestamptz not null default now(),\n  updated_at timestamptz not null default now()\n);\n\ncreate table if not exists auth_sessions (\n  id uuid primary key default gen_random_uuid(),\n  user_id text not null references users(id) on delete cascade,\n  token_hash text not null unique,\n  provider text not null check (provider in ('web_guest', 'web_password')),\n  created_at timestamptz not null default now(),\n  expires_at timestamptz not null,\n  last_used_at timestamptz,\n  revoked_at timestamptz\n);\n\ncreate index if not exists auth_sessions_user_active_idx\n  on auth_sessions(user_id, expires_at)\n  where revoked_at is null;\n";

export const CANONICAL_GAME_MIGRATION_SQL = "create table if not exists game_sessions (\n  session_id text primary key,\n  canonical_state jsonb not null,\n  revision bigint not null check (revision >= 0),\n  created_at timestamptz not null default now(),\n  updated_at timestamptz not null default now()\n);\n\ncreate table if not exists game_session_memberships (\n  session_id text not null references game_sessions(session_id) on delete cascade,\n  principal_id text not null references users(id) on delete cascade,\n  player_id text not null,\n  joined_at timestamptz not null default now(),\n  primary key (session_id, principal_id),\n  unique (session_id, player_id)\n);\n\ncreate table if not exists accepted_command_receipts (\n  session_id text not null references game_sessions(session_id) on delete cascade,\n  command_id text not null,\n  command_fingerprint text not null,\n  actor_player_id text not null,\n  accepted_revision bigint not null check (accepted_revision >= 0),\n  created_at timestamptz not null default now(),\n  primary key (session_id, command_id)\n);\n\ncreate table if not exists game_outbox (\n  outbox_id bigserial primary key,\n  session_id text not null references game_sessions(session_id) on delete cascade,\n  accepted_revision bigint not null check (accepted_revision >= 0),\n  audience jsonb not null,\n  payload jsonb not null,\n  created_at timestamptz not null default now(),\n  published_at timestamptz null,\n  lease_token text null,\n  lease_expires_at timestamptz null\n);\n\ncreate index if not exists game_outbox_unpublished_idx\n  on game_outbox (outbox_id)\n  where published_at is null;\n\ncreate table if not exists game_deadline_jobs (\n  deadline_id text primary key,\n  session_id text not null references game_sessions(session_id) on delete cascade,\n  due_at timestamptz not null,\n  principal_id text not null references users(id) on delete cascade,\n  command_id text not null,\n  command_fingerprint text not null,\n  expected_revision bigint not null check (expected_revision >= 0),\n  command_payload jsonb not null,\n  status text not null check (status in ('pending', 'leased', 'completed')),\n  lease_token text null,\n  lease_expires_at timestamptz null,\n  completed_at timestamptz null\n);\n\ncreate index if not exists game_deadline_jobs_due_idx\n  on game_deadline_jobs (due_at, deadline_id)\n  where status <> 'completed';\n";

export interface SqlClient {
  query(sql: string): Promise<unknown>;
}

export async function applyCanonicalMigrations(client: SqlClient): Promise<void> {
  await client.query(CANONICAL_IDENTITY_MIGRATION_SQL);
  await client.query(CANONICAL_GAME_MIGRATION_SQL);
}
